version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/client
    stdin_open: true
    command: npm run start
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 5000
    image: ecommerce_server
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app/server
    depends_on:
      - database
    environment:
      MONGODB_URI: mongodb://host.docker.internal:27017/Ecommerce
    command: npm run dev

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    