version: '3.8'

services:
  # Node.js backend service
  backend:
    container_name: nodejs-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/server
    depends_on:
      - database
    environment:
      FROM_DOCKER: 'true'
    networks:
      - mern_network

  frontend:
    container_name: reactjs-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/client
    depends_on:
      - backend
    networks:
      - mern_network

  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge
