version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/client
    stdin_open: true
  
  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/server
    depends_on:
      - database

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    